Update - removendo limite de supplies na listagem de abrigos
SOS-RS/backend pull request #136
Opened 2024-05-18 20:18 UTC by xlucaix

### Melhorar a descoberta de que existem mais itens depois que o limite de 10 é excedido no card

Acesse o card pelo [link](https://sosriograndedosul.notion.site/bba977635382411d95adafd32d95417f?v=d7a5ab7c82064286b8b312ad2d32b0a6&p=d208cae935fd4d9899a094dad55c46d9&pm=s)

#### Resumo: 
Eu sou doador. Eu estou tentando entender em profundidade todos os itens que um abrigo específico precisa. Mas não sabia que são inúmeros itens porque pela listagem tive a impressão de que eram só 10 o que faz com que eu não tenha dimensão da verdadeira demanda.

2024-05-21 14:51 UTC, vinny-silveira requested changes
O nome do método `getQuery` foi alterado mas a chamada dele no service não foi ajustada, está dando erro logo ao iniciar o projeto:

![image](https://github.com/SOS-RS/backend/assets/13592890/c434609e-f76a-4264-b321-865aa2f8ce4f)

2024-05-21 21:09 UTC, xlucaix commented
> O nome do método `getQuery` foi alterado mas a chamada dele no service não foi ajustada, está dando erro logo ao iniciar o projeto:
> 
> ![image](https://private-user-images.githubusercontent.com/13592890/332473225-c434609e-f76a-4264-b321-865aa2f8ce4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMjU2NDgsIm5iZiI6MTcxNjMyNTM0OCwicGF0aCI6Ii8xMzU5Mjg5MC8zMzI0NzMyMjUtYzQzNDYwOWUtZjc2YS00MjY0LWIzMjEtODY1YWEyZjhjZTRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIxMDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjZDY1OTcxODIxY2JiYmU1YzM3NTVhZGJmYWNkNjZhNDNkZDdlNjhlY2ZhNTk2NDJiNDlkYWY3NmVjN2NkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pHSTRanXuVNfpocmredrLXYGyus3gmxdoGHymCqHbiE)

Opa @vinny-silveira, acabei de atualizar com a develop

2024-05-22 12:26 UTC, vinny-silveira requested changes
Bom dia @xlucaix, você está rodando o backend local? Pois ainda segue sem funcionar:

![image](https://github.com/SOS-RS/backend/assets/13592890/8f8be9cc-95ce-4fbd-adfd-b0a703d3a759)

Atualizei minha branch local com as suas atualizações e mesmo assim o erro persiste:

![image](https://github.com/SOS-RS/backend/assets/13592890/93e1af96-b854-4546-933f-78e89b503188)

Antes de submeter a PR ou uma nova revisão, peço que minimamente rode o projeto localmente e garanta o funcionamento básico do projeto.

2024-05-22 17:09 UTC, xlucaix commented
@vinny-silveira aqui tinha rodado localmente tranquilo, o que foi estranho kkkk
Depois de comparar o arquivo shelterSearch notei que a classe foi alterada, acredito ter sido erro aqui de alguma extensão local, vou revisar depois qual pode ter feito isso.
Subi um novo commit removendo as alterações da classe e já rodando o projeto

2024-05-22 18:12 UTC, vinny-silveira requested changes
Certo, o problema de execução foi resolvido, porém, as tags não retornam corretamente do BFF, deixando o front dessa forma:

![image](https://github.com/SOS-RS/backend/assets/13592890/59d599f4-f371-4764-a867-d5b22039b167)

Você removeu o `defaultTagsData`, e pelo objeto `tags` da linha 176 ficar vazio, nada é tagueado. Para manter o funcionamento, sugiro que volte o objeto `defaultTagsData` e faça o spread dele como era feito antes:

```ts
  const tags: ShelterTagInfo = {
    ...defaultTagsData,
    ...(tagProps?.tags ?? {}),
  };
```

Novamente, peço que teste o **backend integrado com o front sempre**, e para evitar caches, sempre faça um clear no Chrome pelo Developer Tools:

![image](https://github.com/SOS-RS/backend/assets/13592890/4ebfe6a6-92a8-4d1f-b942-c78b03809395)

Ou sempre teste em abas anônimas.

2024-05-22 21:20 UTC, xlucaix commented
> Certo, o problema de execução foi resolvido, porém, as tags não retornam corretamente do BFF, deixando o front dessa forma:
> 
> ![image](https://private-user-images.githubusercontent.com/13592890/332908602-59d599f4-f371-4764-a867-d5b22039b167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTMwMDEsIm5iZiI6MTcxNjQxMjcwMSwicGF0aCI6Ii8xMzU5Mjg5MC8zMzI5MDg2MDItNTlkNTk5ZjQtZjM3MS00NzY0LWE4NjctZDViMjIwMzliMTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIxMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NjRlOTU0ZWI2MmNiOTYyMjU5NWEwMGQ2NTBjNjM4YWMyNWNkZjJlN2I3ZGNhZTgxNDU3OTI0NWIxYjdiMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iia-1qxpztGHdagnfBnT8IfdU6NlvVfNBePPYVcVVqA)
> 
> Você removeu o `defaultTagsData`, e pelo objeto `tags` da linha 176 ficar vazio, nada é tagueado. Para manter o funcionamento, sugiro que volte o objeto `defaultTagsData` e faça o spread dele como era feito antes:
> 
> ```ts
>   const tags: ShelterTagInfo = {
>     ...defaultTagsData,
>     ...(tagProps?.tags ?? {}),
>   };
> ```
> 
> Novamente, peço que teste o **backend integrado com o front sempre**, e para evitar caches, sempre faça um clear no Chrome pelo Developer Tools:
> 
> ![image](https://private-user-images.githubusercontent.com/13592890/332911304-4ebfe6a6-92a8-4d1f-b942-c78b03809395.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTMwMDEsIm5iZiI6MTcxNjQxMjcwMSwicGF0aCI6Ii8xMzU5Mjg5MC8zMzI5MTEzMDQtNGViZmU2YTYtOTJhOC00ZDFmLWI5NDItYzc4YjAzODA5Mzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDIxMTgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjgyMWNlZDIxNjQwZTRlOTU1NzI5ZmFmNmI4MWYxOTYwZjQ1MjBmOWMzM2U0NjU1MGQyMmE4NTFiNWI4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MoHRS-BW8r001K-P9g0FMXnaRYvndoWco3yU-_ga81k)
> 
> Ou sempre teste em abas anônimas.

Talvez por cache comigo exibia, alterei o sche
ma da tag para boolean, já que o objetivo náo é lidar mais limitar quantidades, acho que agora ta ok, testei várias vezes removendo cache. 

![Screenshot 2024-05-22 at 18 19 47](https://github.com/SOS-RS/backend/assets/166631000/07d26c13-3572-4d3f-a6d7-21f1b01cbff2)

2024-05-23 03:46 UTC, vinny-silveira approved these changes
PR apto ao merge

2024-05-23 12:26 UTC, vinny-silveira commented
@SOS-RS/backenders , preciso de mais um review aqui.

2024-06-01 23:57 UTC, larissapissurno approved these changes
lgtm

2024-06-01 23:58 UTC, merged