feat: add min node version to install dependencies
SOS-RS/backend pull request #149
Opened 2024-05-19 20:43 UTC by Mikael-R

2024-05-20 16:21 UTC, rodrigooler requested changes

2024-05-20 16:21 UTC, rodrigooler commented on package.json
> +  "engines": {
@Mikael-R poderia adicionar também a versão mínima do npm?

2024-05-20 22:31 UTC, Mikael-R commented on package.json
> +  "engines": {
@rodrigooler Adicionado 😉

2024-05-20 23:42 UTC, rodrigooler commented
PR resolve o problema da issue https://github.com/SOS-RS/backend/issues/134

2024-05-21 02:46 UTC, iagxferreira approved these changes

2024-05-21 12:15 UTC, marcieltorres approved these changes

2024-05-23 21:34 UTC, fagundesjg approved these changes

2024-05-23 21:34 UTC, merged