test: cover getMany and create for partners entity
SOS-RS/backend pull request #154
Opened 2024-05-20 02:12 UTC by BertBR

- Melhora a cobertura de testes para a entidade `Partner`

2024-05-20 23:37 UTC, rodrigooler approved these changes

2024-05-21 02:30 UTC, giggio requested changes

2024-05-21 02:30 UTC, giggio commented on src/partners/partners.service.spec.ts
> +    expect(service).toBeDefined();
Essa linha pode ser removida, e tá faltando o assert.

2024-05-23 19:16 UTC, giggio commented
@BertBR eu gostaria de integrar isso aí, vou revisar suas alterações.

2024-05-23 19:19 UTC, giggio approved these changes
Agora está ok, bora integrar.

2024-05-23 19:19 UTC, merged