feat: initial item_update_logs implementation
SOS-RS/backend pull request #161
Opened 2024-05-22 04:42 UTC by risaddex

[Histórico de Modificações dos Itens do Abrigo](https://github.com/SOS-RS/backend/issues/146)
#146

Implementação inicial que fecha a #146

- [x] método "updateAndAudit" criado
- [] método "updateAndAuditMany" criado

Além disso também deixei esquematizado um audit genérico caso achem válido. Caso contrário removo do PR dps de fechar o draft

2024-05-22 13:00 UTC, rhuam commented
@risaddex pode só alterar o nome da tabela para supplies_history, por gentileza. Foi uma sugestão pertinente do @giggio que ajuda a entender o que essa tabela armazena de fato.

2024-05-23 19:03 UTC, giggio commented on .env.test
> +DB_PASSWORD=postgres
Como o usuário e a senha deste arquivo estão diferentes dos que estão no `.env.local`, que é a base do setup de dev, ao rodar os testes o login no banco de dados falha. Seria importante manter igual, como `root` para os dois valores.

2024-05-23 19:06 UTC, giggio requested changes
Estou com erro ao rodar os testes:

```
> dotenv -e .env.test -- jest --config ./test/jest.e2e.config.ts

 FAIL  test/app.e2e-spec.ts
  ● Test suite failed to run

    test/app.e2e-spec.ts:80:30 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.

    80     const log = await prisma.suppliesHistory.findFirst({
                                    ~~~~~~~~~~~~~~~
    test/app.e2e-spec.ts:108:33 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.

    108     const before = await prisma.suppliesHistory.count();
                                        ~~~~~~~~~~~~~~~
    test/app.e2e-spec.ts:119:32 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.

    119     const after = await prisma.suppliesHistory.count();
                                       ~~~~~~~~~~~~~~~
    test/app.e2e-spec.ts:120:42 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.

    120     const suppliesHistory = await prisma.suppliesHistory.findMany({
                                                 ~~~~~~~~~~~~~~~
    test/app.e2e-spec.ts:211:12 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.

    211     prisma.suppliesHistory.deleteMany(),
                   ~~~~~~~~~~~~~~~

Test Suites: 1 failed, 1 total
```

2024-05-23 20:49 UTC, risaddex commented
> Estou com erro ao rodar os testes:
> 
> ```
> > dotenv -e .env.test -- jest --config ./test/jest.e2e.config.ts
> 
>  FAIL  test/app.e2e-spec.ts
>   ● Test suite failed to run
> 
>     test/app.e2e-spec.ts:80:30 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> 
>     80     const log = await prisma.suppliesHistory.findFirst({
>                                     ~~~~~~~~~~~~~~~
>     test/app.e2e-spec.ts:108:33 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> 
>     108     const before = await prisma.suppliesHistory.count();
>                                         ~~~~~~~~~~~~~~~
>     test/app.e2e-spec.ts:119:32 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> 
>     119     const after = await prisma.suppliesHistory.count();
>                                        ~~~~~~~~~~~~~~~
>     test/app.e2e-spec.ts:120:42 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> 
>     120     const suppliesHistory = await prisma.suppliesHistory.findMany({
>                                                  ~~~~~~~~~~~~~~~
>     test/app.e2e-spec.ts:211:12 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> 
>     211     prisma.suppliesHistory.deleteMany(),
>                    ~~~~~~~~~~~~~~~
> 
> Test Suites: 1 failed, 1 total
> ```

Boa. Creio que faltou colocar o "prisma migrade deploy" antes de executar o teste. (achava que rodava antes na pipeline, por isso não mencionei)

2024-05-23 20:53 UTC, risaddex commented
> > Estou com erro ao rodar os testes:
> > ```
> > > dotenv -e .env.test -- jest --config ./test/jest.e2e.config.ts
> > 
> >  FAIL  test/app.e2e-spec.ts
> >   ● Test suite failed to run
> > 
> >     test/app.e2e-spec.ts:80:30 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> > 
> >     80     const log = await prisma.suppliesHistory.findFirst({
> >                                     ~~~~~~~~~~~~~~~
> >     test/app.e2e-spec.ts:108:33 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> > 
> >     108     const before = await prisma.suppliesHistory.count();
> >                                         ~~~~~~~~~~~~~~~
> >     test/app.e2e-spec.ts:119:32 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> > 
> >     119     const after = await prisma.suppliesHistory.count();
> >                                        ~~~~~~~~~~~~~~~
> >     test/app.e2e-spec.ts:120:42 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> > 
> >     120     const suppliesHistory = await prisma.suppliesHistory.findMany({
> >                                                  ~~~~~~~~~~~~~~~
> >     test/app.e2e-spec.ts:211:12 - error TS2339: Property 'suppliesHistory' does not exist on type 'PrismaService'.
> > 
> >     211     prisma.suppliesHistory.deleteMany(),
> >                    ~~~~~~~~~~~~~~~
> > 
> > Test Suites: 1 failed, 1 total
> > ```
> 
> Boa. Creio que faltou colocar o "prisma migrade deploy" antes de executar o teste. (achava que rodava antes na pipeline, por isso não mencionei)

Na verdade meu eu do passado tinha me ajudado, colocando o "pre" hook do npm. Ocorre mesmo usando o "npm run test:e2e" ?

2024-05-23 20:56 UTC, risaddex commented on .env.test
> +DB_PASSWORD=postgres
Opa, total razão. Foi deslize aqui com a minha conf local. De qualquer forma a ideia era evitar que alguém rodasse os testes de integração no ambiente de staging e limpasse a base por engano :+1:

2024-05-23 21:28 UTC, closed without merging

2024-05-23 22:27 UTC, fagundesjg commented
Para formalizar o fechamento do PR, vou colar aqui a resposta oficial do @rhuam que foi dada ao author no grupo do discord:

"optamos por uma solução com menos complexidade de código, onde a regra de negócio ficasse no banco de dados de forma nativa, sem usar JSON para armazenar dados. Sua solução estava ótima, mas acreditamos que a #162 performa melhor e é mais fácil para dar manutenção."