Quality of life: implement some quality of life updates reg Docker
SOS-RS/backend pull request #42
Opened 2024-05-10 17:36 UTC by coelhotatiane

**O QUE CONSTA NO PR:**

- Remove variáveis hardcoded no docker compose. Agora o .env é a única fonte de informações e se precisar alterar será em um único lugar.
- Adiciona configuração de _watchOptions_ em tsconfig.json que permite que a flag --watch funcione rodando com Docker. Agora qualquer modificação no código será automaticamente refletida sem a necessidade de descer o container e subir novamente.
- A versão do node considerada no docker compose foi atualizada também no Docker file para evitar conflitos.

**EVIDÊNCIAS DE FUNCIONAMENTO:**
Logs:
![image](https://github.com/SOS-RS/backend/assets/53581377/7f8c073a-8997-4bf1-b2ab-1beac70e7b65)

**COMO TESTAR**
Rode o servidor normalmente com o docker compose e acesse algum endpoint (ex.: http://localhost:4000/shelters). Experimente trocar a mensagem da resposta padrão de "Successfully get shelters" para alguma outra para ver a alteração mais facilmente.

2024-05-10 22:20 UTC, filipepacheco approved these changes
good job

2024-05-10 22:27 UTC, filipepacheco requested changes
na verdade podemos tirar os dois environments que funciona normalmente, o docker pega direto do nosso .env

2024-05-11 02:38 UTC, filipepacheco approved these changes

2024-05-11 15:58 UTC, rafaelss approved these changes

2024-05-11 16:55 UTC, merged