Add formatting and linting checks to CI
SOS-RS/backend pull request #48
Opened 2024-05-10 20:15 UTC by sombraSoft

- added `lint:ci` script in `package.json` to run in CI
- created CI workflow for github actions. It will now run for all PRs for `develop` and `master` branches
- fixed 3 files that had lint warnings

2024-05-10 20:18 UTC, AndersonCRocha commented on .github/workflows/ci.yml
> +        run: npm run lint
Não seria o lint:ci?

2024-05-10 20:32 UTC, sombraSoft commented on .github/workflows/ci.yml
> +        run: npm run lint
sim! vou arrumar

2024-05-10 20:43 UTC, AlbuquerqueRafael requested changes
Obrigado pelo PR @sombraSoft.

2024-05-10 20:43 UTC, AlbuquerqueRafael commented on .github/workflows/ci.yml
> +        env:
Você poderia mudar sua implementação para utilizar a action abaixo? Facilitará a manutenção de forma geral:
- https://github.com/actions/setup-node

Também considere utilizar 'npm ci' ao invés de 'npm install'.
Ex abaixo:


```
 # Check out the source
      - name: Checkout Source
        uses: actions/checkout@v4
      # Setup node.js, Install and Build App
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # Lint App
      - name: Lint App
        run: npm run lint -
      # Build App
      - name: Build App
        run: npm run build 
```

2024-05-10 20:55 UTC, sombraSoft commented on .github/workflows/ci.yml
> +        env:
não conhecia essa feature do `setup-node`.. bem mais simples!

2024-05-10 21:00 UTC, sombraSoft commented on .github/workflows/ci.yml
> +        env:
pronto, agora está chamando `npm run lint:ci`

2024-05-10 21:00 UTC, sombraSoft commented on .github/workflows/ci.yml
> +        env:
pode fazer rodar o workflow desse PR pra testar?

2024-05-10 21:04 UTC, AlbuquerqueRafael commented on .github/workflows/ci.yml
> +        env:
Eu consigo testar utilizando https://github.com/nektos/act. Apenas estou verificando a questão de billing agora.

2024-05-10 22:32 UTC, AlbuquerqueRafael approved these changes

2024-05-11 03:01 UTC, filipepacheco approved these changes

2024-05-11 15:13 UTC, sombraSoft commented
@filipepacheco resolvi os conflitos, tá pronto pra subir

2024-05-11 16:59 UTC, merged