Add address details in shelters
SOS-RS/backend pull request #6
Opened 2024-05-08 21:53 UTC by pedroperrone

Add `street`, `neighbourhood` and `city` so the fields can be used in searches such as needed supplies by neighbourhood

2024-05-08 21:54 UTC, pedroperrone commented
Do you think it's worth adding the street number as well?

2024-05-08 23:36 UTC, filipefraga commented
> Do you think it's worth adding the street number as well?

Yes, and also zipcode.

2024-05-08 23:38 UTC, filipefraga requested changes
looks good, apenas acredito que falte number e zipcode

2024-05-08 23:53 UTC, mayrahmelo commented
Oi pessoal, não sei como está o desenvolvimento do mapa, mas se precisarem acredito que todas as infos de localização e alocação fiscal (CEP, números e detalhes mais profundos etc), vocês conseguem no Geoportal RS.

Dei uma olhada por cima no projeto, não sei em qual profundidade o projeto vai chegar, mas dependendo, seria bacana ter um espaço onde as pessoas conseguem incluir fotos dos pets que estão em determinados abrigos, assim algumas pessoas podem checar se encontram seu pet perdido em outro abrigo. Mesma coisa para pessoas, considerando que podem haver pessoas que foram resgatadas em bairros diferentes e levadas para abrigos longe dos familiares.

Queria parabenizá-los pela ideia, o projeto é muito legal e tenho certeza que vai ajudar demais nesse momento!
Se precisarem de ajuda com ideias, ou Marketing para o projeto (para que consigam mais pessoas para colocar a mão na massa no desenvolvimento) ou mesmo para compartilhamento nas redes e centralização das informações, estou à disposição!

2024-05-09 01:15 UTC, filipepacheco approved these changes

2024-05-10 23:06 UTC, MatheusDubin approved these changes

2024-05-12 01:07 UTC, filipepacheco commented
Fechando aqui pois tá rolando conflito de merge e de migrations.
Migrei pro https://github.com/SOS-RS/backend/pull/6 e coloquei @pedroperrone como author do commit e resolvi os conflitos.

2024-05-12 01:07 UTC, closed without merging