fix: Adjusted sql file name to reflect reality
SOS-RS/backend pull request #64
Opened 2024-05-11 16:38 UTC by w-araujo

### 🤔 O que foi feito?

Foi alterado no readme o nome do arquivo .sql para refletir o nome real do arquivo que está na pasta "prisma".

### 📗 Checklist do desenvolvedor

- [x]  Foi testado localmente?
- [x]  Foi adicionado documentação necessária (swagger, testes e etc)? Sim, no readme

### 👀 Checklist do revisor
**Revisor 1️⃣**

- [ ]  Você entendeu o propósito desse PR?
- [ ]  Você entendeu o fluxo de negócio?
- [ ]  Você entendeu o que e como foi desenvolvido tecnicamente a solução?
- [ ]  Você analisou se os testes estão cobrindo a maioria dos casos?

### 🔗 Referênia

2024-05-15 00:54 UTC, lucaskdc commented
PR duplicado sobre mesmo assunto: https://github.com/SOS-RS/backend/pull/91

2024-05-15 00:55 UTC, lucaskdc commented on README.md
> +docker exec -it cp dev_dump.sql POSTGRES_CONTAINER_ID:/tmp/backup.sql
this command doesn't work, as reviewd by [brunousml](https://github.com/brunousml) in the PR https://github.com/SOS-RS/backend/pull/91

2024-05-15 02:36 UTC, lucaskdc commented
Verificar issue https://github.com/SOS-RS/backend/issues/109

2024-05-15 02:39 UTC, gabrielbrise commented
Para mudar o nome para refletir o nome atual, precisa ser alterado em ambos comandos. O PR https://github.com/SOS-RS/backend/pull/84 faz isso da maneira certa. Caso queira que seja usado o nome igual ao do arquivo em todas etapas do processo de dump, sugira a alteração dentro daquele PR. Não há necessidade de um PR separados mechendo nas mesmas linhas pois no fim vão gerar conflitos

2024-05-15 02:42 UTC, gabrielbrise requested changes
Needs changes in both commands to work. My suggestion is to close this PR and suggest changes at PR https://github.com/SOS-RS/backend/pull/84

2024-05-20 01:21 UTC, giggio commented
Duplicado do #84 que já foi integrado.

2024-05-20 01:21 UTC, closed without merging