Add prisma seed for dev dump
SOS-RS/backend pull request #66
Opened 2024-05-11 18:22 UTC by rkperes

Add prisma seed for dev dump.
Update scripts to run it automatically in docker-compose.

2024-05-11 18:26 UTC, mgrithm requested changes

2024-05-11 18:26 UTC, mgrithm commented on docker-compose.dev.yml
> +    # # remover comentário para expor DB para localhost
Por questão de semântica, seria bom não manter comentários no código e principalmente no docker-compose.

2024-05-11 18:26 UTC, mgrithm commented on prisma/seed.ts
Roda um prettier pra deixar tudo indetado e não ficar com mais de 2 espaços. Novamente, seria bom não manter comentários no código.

2024-05-13 01:47 UTC, mgrithm approved these changes
lgtm

2024-05-13 01:50 UTC, mgrithm commented
@filipepacheco, da uma olhada aqui

2024-05-13 11:24 UTC, antoniolucasnobar approved these changes

2024-05-20 01:35 UTC, giggio requested changes
Estou recebendo erros ao rodar, por exemplo:

```
Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.$executeRawUnsafe()` invocation:


Raw query failed. Code: `42601`. Message: `ERROR: unterminated quoted string at or near "e'4f95853f-d5e1-487d-8086-6ddfaf2bbab7"`
```

2024-05-20 01:35 UTC, giggio commented on package.json
> +    "migrations:dev": "npx prisma migrate dev && npx prisma db seed",
Não é necessário rodar o `prisma deb seed`, ele roda sozinho após o `prisma migrate dev`.
O que seria legal é retirar o `npx` dos dois comandos, que é desnecessário, já que os comandos do npm rodam sob o contexto do `node_modules/bin` no path.

2024-09-25 17:09 UTC, rkperes commented
Since is by now pretty old.
Let me know if you want me to come back to it.

2024-09-25 17:09 UTC, closed without merging